name: Data Archive Models CI

# Triggers the workflow on pushes to the 'main' branch, pull requests targeting 'main',
# release creation, and also allows manual triggering via the GitHub Actions UI.
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'        # Ignores README.md in the root directory
  pull_request:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Runs the dedicated unit tests for schema validation.
  # This job executes only after the Nix environment has been successfully set up.
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Nix with Flakes Support (for this job)
        # Each job in GitHub Actions runs in an isolated environment.
        # Therefore, Nix needs to be installed again for this job's context.
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Execute Specific Schema Validation Tests
        # Runs the Maven test command within the Nix development shell.
        # This ensures that tests related to 'JsonSchemaValidationTest' are executed
        # using the Java and Maven versions specified in your Nix configuration.
        run: nix develop --command mvn -Dtest=JsonSchemaValidationTest test

  # Generates Java models from the JSON schemas.
  # This job proceeds only if the unit tests have passed successfully.
  generate-java-models:
    name: Generate Java Models
    runs-on: ubuntu-latest
    needs: run-unit-tests # Ensures this job only starts after all tests have passed.
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Nix with Flakes Support (for this job)
        # Nix needs to be installed for this independent job as well to ensure the environment is ready.
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Generate Java Classes from JSON Schemas
        # Executes the Maven package phase within the Nix development shell.
        # This will trigger 'jsonschema2pojo' to generate your Java classes.
        # Tests are skipped as they were already run in the 'Run Unit Tests' job.
        run: nix develop --command mvn package -DskipTests

      - name: Upload Maven target directory
        # This step preserves the compiled Java classes and built JAR from this job
        # to be used in the publish-to-github-packages job.
        # This is necessary because GitHub Actions jobs run in isolated environments,
        # and without this step, the compiled classes would not be available for deployment.
        uses: actions/upload-artifact@v4
        with:
          name: maven-target
          path: target/
          retention-days: 1

  # Publishes the Java .jar artifacts to GitHub Packages
  publish-to-github-packages:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: generate-java-models # Ensures this job only starts after the Java models have been generated
    # Only run this job when pushing to the main branch, creating a release, or manually triggered
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' || github.event_name == 'release'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Nix with Flakes Support (for this job)
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Download Maven target directory
        # This step retrieves the compiled Java classes and built JAR from the generate-java-models job
        # and places them in the target/ directory of this job's workspace.
        # This ensures that the mvn deploy command has access to the complete artifact for deployment,
        # solving the issue of empty JARs being deployed due to isolated job environments.
        uses: actions/download-artifact@v4
        with:
          name: maven-target
          path: target/

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configure Maven for GitHub Packages
        # This step dynamically creates a Maven settings.xml file with GitHub Packages authentication.
        # It's necessary because 'nix develop' doesn't automatically configure Maven like 'setup-java'.
        #
        # Security Note:
        # - The settings.xml file is created temporarily in the runner's ephemeral environment.
        # - It is automatically destroyed after the job completes, preventing persistent storage of credentials.
        # - The GITHUB_TOKEN (accessed via secrets.GITHUB_TOKEN) is automatically masked in logs by GitHub.
        run: |
          # Create the .m2 directory if it doesn't exist
          mkdir -p ~/.m2

          # Write the settings.xml content using a "here-doc" for clean multi-line output
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id> <!-- This ID must match the <id> in your pom.xml's <distributionManagement> -->
                <username>${{ github.actor }}</username> <!-- Uses the GitHub user/bot that triggered the workflow -->
                <password>${{ secrets.GITHUB_TOKEN }}</password> <!-- Uses the auto-generated, short-lived GITHUB_TOKEN -->
              </server>
            </servers>
            <profiles>
              <profile>
                <id>github</id>
                <repositories>
                  <repository>
                    <id>github</id>
                    <url>https://maven.pkg.github.com/eth-library/data-archive-models</url>
                    <snapshots>
                      <enabled>true</enabled>
                    </snapshots>
                  </repository>
                </repositories>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>github</activeProfile>
            </activeProfiles>
          </settings>
          EOF
        env:
          # Explicitly pass GITHUB_TOKEN to the environment, though it's primarily
          # consumed by Maven via the settings.xml configuration.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Packages
        # Executes the Maven deploy goal within the Nix development shell.
        # This will publish the artifact to GitHub Packages.
        # The GITHUB_TOKEN is used for authentication.
        run: nix develop --command mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Publishes Python package to TestPyPI (runs in parallel with GitHub Packages)
  publish-to-testpypi:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    needs: run-unit-tests
    # Only run this job when pushing to the main branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Fetch all history for proper versioning
          fetch-depth: 0

      - name: Install Nix with Flakes Support
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Retrieve Dynamic Version
        id: version
        run: |
          # Generate a PEP 440 compliant version string using current date and run number
          # Format: YYYY.MM.DD.dev<RUN_NUMBER>
          VERSION=$(date -u +%Y.%m.%d.dev${{ github.run_number }})
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Retrieved version: $VERSION"

      - name: Generate Python Models from Schemas
        run: |
          # Enter the Nix development shell and run the code generation commands
          nix develop --command bash -c '
            # Ensure the output directory exists
            mkdir -p src/data_archive/

            # Generate Python models from JSON schemas
            echo "Generating Python models from JSON schemas..."

            # Execute datamodel-codegen with the following parameters:
            # --input-file-type: Specifies the input file type as JSON schema
            # --input: Path to the directory containing JSON schema files
            # --output: Path where the generated Python models will be saved
            # --output-model-type: Specifies the base class for generated models (Pydantic v2)
            # --field-constraints: Adds validation based on JSON schema constraints
            # --use-schema-description: Uses schema descriptions for class docstrings
            datamodel-codegen \
              --input-file-type jsonschema \
              --input schemas/data-archive/ \
              --output src/data_archive/ \
              --output-model-type pydantic_v2.BaseModel \
              --field-constraints \
              --use-schema-description

            # List generated files for verification
            echo "Generated Python models:"
            ls -la src/data_archive/
          '

      - name: Build and Publish to TestPyPI
        run: |
          # Enter the Nix development shell and run the build and publish commands
          nix develop --command bash -c '
            # Show value HATCH_VERSION variable in shell
            echo "HATCH_VERSION: $HATCH_VERSION"

            # Build the package
            echo "Building package..."
            uv build --index-strategy unsafe-best-match

            # Publish to TestPyPI
            echo "Publishing to TestPyPI..."
            uv publish --index testpypi
          '
        env:
          HATCH_VERSION: ${{ env.VERSION }}
          # Pass the TestPyPI API token to the environment
          UV_PUBLISH_TOKEN: ${{ secrets.TESTPYPI_API_TOKEN }}
